version: '3'

services:

  db:
    container_name: postgres
    image: postgres:16.6-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=userX
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgres/data
      - ./db/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
